### ISSUE TITLE
errorCount throwing an error

### ISSUE THREAD

**Issue by aljones15** [sasstools/sass-lint#1090]
What version of Sass Lint are you using?
1.10.2

Please include any relevant parts of your configuration

What did you do? Please include the actual source code causing the issue.
just ran the linter on my main.scss file

What did you expect to happen?
it should have outputted the errors

What actually happened? Please include any error messages given to you by Sass Lint.

throw new exceptions.SassLintFailureError(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
SassLintFailureError: 51 errors were detected in 
- src/style/main.scss
    at Function.sassLint.failOnError (/Users/andrewjones/Documents/codePen/did/darkdiner/node_modules/sass-lint/index.js:313:11)
    at detectPattern (/Users/andrewjones/Documents/codePen/did/darkdiner/node_modules/sass-lint/bin/sass-lint.js:31:10)
    at Object.<anonymous> (/Users/andrewjones/Documents/codePen/did/darkdiner/node_modules/sass-lint/bin/sass-lint.js:79:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)

If you're using a IDE plugin have you tried the CLI too?

**Comment by DanielSundberg** [comment]
I also get this on first try. Have you solved this or just moved on?

**Comment by aljones15** [comment]
no and this project doesn't seem to be active eiher so just uninstalled it I believe.

**Comment by AndyTyurin** [comment]
Have you tried to use this command to validate your .scss files
`node ./node_modules/.bin/sass-lint -v -q`
**There you should focus on `-v -q` flags.**

Also in common you can stuck with another problem of max errors limitation settings.
If one of the published configs I saw limitation of 50 errors as a maximum.

**Comment by DanPurdy** [comment]
@aljones15 and @DanielSundberg This looks like @AndyTyurin has hit the nail on the head. Check your configs and how you're running Sass-lint. If you post those and the commands you're using and report back we can look into it a little bit more.

**Comment by DanPurdy** [comment]
It's clearly described in the readme and the docs though so I'm not sure what else can be done to help if you haven't read them..

**Comment by DanielSundberg** [comment]
In my opinion running "sass-lint" with default sample config should result in an error message I can understand without reading documentation. 

If you don't agree with that I that's fine with me, just wanted to contribute here.

**Comment by DanPurdy** [comment]
I'm sorry you feel that way but i can't understand why you refer to it as an issue when it's clearly described in the docs and the readme.. By design it may not be the friendliest first experience agreed, but until we move into a new major version I'm afraid that's what we're stuck with, if you have feedback or a solution then please open an issue and describe what you think the default should be and what flags should be used to get our current default behaviour or at least start the discussion around it in the relevant places so we can address these issues for new users going forward..

We give the RTFM as you call it because it's the reason we wrote them and invested a lot of time into them, to help new users such as yourself and it takes more time to answer issues frequently where people haven't read through the readme properly which is the reason why so many projects like this end up abandoned because our inboxes and notifications get jammed up. We're happy you contributed and glad you've solved your issue and if you feel there's a better solution than what we have now then please raise an issue or suggestion to start a discussion about where to go next.

**Comment by DanielSundberg** [comment]
@DanPurdy, thanks for taking the time to write your reply, of course I can understand your point since also been on your side on a number of projects.

**Comment by Sweet-Bob** [comment]
sass-lint -v -q ;)

**Comment by mrlubos** [comment]
@DanPurdy Have you moved to a new major version yet? Just run into the same issue.
