### ISSUE TITLE
New Rule: Unnecessary Mantissa

### ISSUE THREAD

**Issue by Dru89** [sasstools/sass-lint#438]
Name: `unnecessary-mantissa`

Add a rule that enforces that removal of all unnecessary trailing decimal points (e.g. `4.0` should be written as `4`).

I was a little ambitious and have already written the code to complete this as [`a7db54b`](https://github.com/Dru89/sass-lint/commit/a7db54b6b910e3f7ce6623a2c1d9eca7c5fcc017) but will wait to submit the pull request as per the contributing guidelines.

**Comment by Snugug** [comment]
Per our rule naming conventions, if this is a strict disallow it should be named:

no-disallowed-thing

In addition, we prefer as simple language as possible, so instead of the technical mantissa I'd prefer decimal (or similar) so the rule name should be something like 

no-unnecessary-decimals

Otherwise, yah, I'm ok with adding this rule.

**Comment by DanPurdy** [comment]
I honestly thought no trailing zero should (and did cover this) In my head it should but yeah it actually makes sense to have this as a separate rule.

no-unnecessary-decimals would be the name i would go for too.

**Comment by Dru89** [comment]
Looking at this a bit more, it might actually make sense to modify [`no-trailing-zero.js`](https://github.com/sasstools/sass-lint/blob/develop/lib/rules/no-trailing-zero.js) to cover this use case, as they're kind of the same in my opinion.

What would you think about updating that rule, or should this be considered separate (or perhaps an option)?

**Comment by DanPurdy** [comment]
Yeah definitely, our whole ethos with `sass-lint` is for small single purpose rules and I think to add this to `no-trailing-zero` would mean adding extra options which would be a shame.

With this as a separate rule it would allow people to enforce usage of requiring at least one zero after a decimal but not unneccessary trailing zeros after that.

And yes @Dru89 you're right, after I posted that comment last night I checked our existing rule and it does only work if you have at least one non zero number. I'll create another issue now.

**Comment by Snugug** [comment]
I see a potential lint loop here if you require the ending zero and also have no trailing zeros enabled. Thoughts Dan?

**Comment by DanPurdy** [comment]
Yeah, I think that's a possibility, maybe we should keep it in `no-trailing-zero` then and just have that by default enforce unnecessary 0 values after a decimal.. Would make sense, i dont think requiring the option to allow `margin: 1.0` would make sense after all.

Sooooo update the rule rather than a new one?

**Comment by Nirazul** [comment]
*just came here to say that i love the expression "mantissa"*

**Comment by Snugug** [comment]
Yah, update the rule I think.

**Comment by BPScott** [comment]
Yarp `margin: 1.0` totally counts as an unwanted trailing 0 in my mind. I can't think why I'd want 'margin: 1.0' to be allowed, but 'margin: 1.00' to be invalid. Update the existing rule.

**Comment by alfaproject** [comment]
I agree with fixing the existing rule.
