### ISSUE TITLE
Enhancement: Bang whitespace rules should consider !global flag

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#56]
The Space Before Bang and Space After Bang rules consider both the `!important` and `!default` flag but should also consider the `!global` flag too.

This is currently blocked by the [Gonzales-pe](https://github.com/tonyganch/gonzales-pe) dependency.

**Comment by DanPurdy** [comment]
Confirmed as parsing correctly in gonzales 3.2.1

**Comment by skyred** [comment]
So, we just need to update package.json:

````
"gonzales-pe": "^3.2.1",
````

**Comment by DanPurdy** [comment]
Unfortunately if you do that it will break a lot of other features in `sass-lint` as it stands. `gonzales-pe 3.2.1` includes some breaking features and also some regressions over its previous versions which is why we haven't updated yet.. Once it updates to a stable version with regards to our needs we'll be moving up.

**Comment by skyred** [comment]
Can we list the road blockers from the upstream below:

1. https://github.com/tonyganch/gonzales-pe/issues/134

What else?

**Comment by DanPurdy** [comment]
Sorry this issue is specifically for the global flag errors they wont be listed here. The blockers are opened as issues on the `gonzales-pe` repository if not specified here. Once the issues we know about are resolved we'll then start running our tests again with the new build.

**Comment by DanPurdy** [comment]
This is fixed in sass-lint 1.6.0
