### ISSUE TITLE
Property `overflow-scrolling` appears to be spelled incorrectly

### ISSUE THREAD

**Issue by thalseth** [sasstools/sass-lint#693]
-webkit-overflow-scrolling: touch;  triggers warning:  "Property `overflow-scrolling` appears to be spelled incorrectly".

Is this correct behaviour?

**Comment by bgriffith** [comment]
Hey @thalseth - Thanks for the report. I've just checked and that property is missing from the list of valid property names. Super quick fix! Happy to accept a PR or I'll get it fixed today.

**Comment by bgriffith** [comment]
Ok just to follow up - since it's a non-standard property (https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling), you'll want to add it as an 'extra property for the `no-misspelled-properties` rule - https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-misspelled-properties.md - Any problems, let me know.

**Comment by thalseth** [comment]
Awesome @bgriffith. Thanks for the quick response! 
Config: 
`
no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'overflow-scrolling'
`

**Comment by bgriffith** [comment]
No problem :+1:

**Comment by LaurentGoderre** [comment]
Nice! That just solved my problem!

**Comment by younes-codes** [comment]
warning  Property `scrollbar-width` appears to be spelled incorrectly  no-misspelled-properties

scrollbar-width : used for firefox
