### ISSUE TITLE
no-url-protocols doing more than checking protocols

### ISSUE THREAD

**Issue by danwaz** [sasstools/sass-lint#813]
I feel like this rule is overloaded. A user should be able to check for protocols separately from domains.  I'd recommend adding configuration that could enable/disable the two parts of this rule or creating a separate rule that handles the domain check.

sass-lint@1.8.2

**Comment by DanPurdy** [comment]
HI @danwaz I completely agree with you. Our aim has always been for small single purpose rules and therefore I think your suggestion would perfectly suit this mindset. This would present a breaking change though so I propose maybe the following. 

1. We keep the rule working as is but we add a flag such as 'enforce-domains` too which would be on by default.
1. We add the no-url-domains rule to mimic that functionality also and enable it in our default config
1. We document that as of v2 of sass-lint the option in 1 would be removed and `no-url-protocols` would only check for url protocols and no longer check domains.

The above should give a smooth transition to existing users of the rule while also not breaking anything for those not keeping up with our changelogs. Would that sound fair?

Also on a side note we've all been a little busy which is why not much activity has happened here recently so as usual we'd be happy to see PR's for any of this from anyone interested.

**Comment by danwaz** [comment]
Thanks @DanPurdy.  This sounds like a solid path forward.  I don't mind taking on the work and getting this into PR.  Also a bit busy on my end, but I'll see what I can do.
