### ISSUE TITLE
CLI outputs invalid JSON when detecting multiple targets

### ISSUE THREAD

**Issue by brentlintner** [sasstools/sass-lint#955]
Steps to reproduce:

1. Create a folder `foo`.
2. Create `foo/1.scss` and `foo/2.scss` with `#foo { color: red }`)
3. Run `sass-lint -q -v -f json foo/*`.

What did you expect to happen?

It to print a single array.

What actually happened?

It prints numerous arrays, resulting in invalid json if you try to parse the complete stdout.

Example:

![selection_016](https://cloud.githubusercontent.com/assets/93340/20324533/f85eb070-ab4e-11e6-9253-21547761bc32.png)

Note: I think I found the issue in `bin/sass-lint.js`. I currently have a [commit](https://github.com/brentlintner/sass-lint/commit/e431ad571722f518de8f67dc721647752c528f47) in my fork where I did a quick fix to get things moving for the project I'm working on.

Hope this helps, and thanks for the awesome project.  :-)

**Comment by DanPurdy** [comment]
@brentlintner thanks for this. I really really don't know how this has gone under the radar for so long or how we've never noticed it! Unfortunately due to our lack of time over the last year or so this has gone unfixed too.. We are going to be bringing out a v2 very shortly, mainly to deprecate older node versions and this fix will be part of that update as im worried that with the lack of other people reporting this as an issue they've worked around it or just not noticed either..

It explains a problem we noticed in the gulp plugin though but which we didn't have time to investigate properly...

**Comment by brentlintner** [comment]
@DanPurdy no problem! Kudos on the new release as well, and thanks. :-)
